---
- hosts: localhost
  connection : local
  gather_facts: false


  tasks:
    - name: Get playbook variables
      include_vars:
        file: vars.yml
    - name: VM_name
      debug:
       msg: "{{ VM_name }}"
    - name: VM_size
      debug:
       msg: "{{ VM_size }}"
    - name: VM_Offer
      debug:
       msg: "{{ Image_offer }}"

    - name: Create virtual network
      local_action:
        module: azure_rm_virtualnetwork
        resource_group: "{{ RG }}"
        name: snowvnet
        address_prefixes: "10.10.0.0/16"
        #subscription_id: "{{ subscription_id }}"
        #client_id: "{{ Client_id }}"
        #secret: "{{ Secret_key }}"
        #tenant: "{{ Tenant_id }}"

    
