---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: RG-GS
    vm_name: Service Now
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowteam18!
    subscription_id: e67e058e-9b7d-4256-b9d9-6cef549a2436
    Client_id: 0e1af58d-fb21-442b-ac99-b5a070cc3e13
    Secret_key: wOOx2fE0O6Gn5lKVtZsGytw8ojrBAlZNofkl5ZDaYos=
    Tenant_id: 400b47ce-ffad-4d65-bdf3-1a2f5312e597


  tasks:
    - name: Add tower Credential for Azure 
      tower_credential:
        name: azure
        kind: azure_rm
        description: azure
        organization: "Default"
        state: present
        subscription_id: "{{ subscription_id }}"
        client_id: "{{ Client_id }}"
        secret: "{{ Secret_key }}"
        tenant: "{{ Tenant_id }}"
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ RG }}"
        name: testvn001
        address_prefixes: "10.10.0.0/16"
        #subscription_id: "{{ subscription_id }}"
        #client_id: "{{ Client_id }}"
        #secret: "{{ Secret_key }}"
        #tenant: "{{ Tenant_id }}"
    - name: create virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ RG }}"
        name: "{{ vm_name }}"
        vm_size: "{{ size }}"
        admin_username: "{{ admin_uname }}"
        admin_password: "{{ admin_passwd }}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
