---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    name_vm: "{{ the_name_vm }}"
    RG: myResourceGroup
    vm_name: TestOfficiel
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis
    
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ RG }}"
        name: '{{ the_name_vm }}'
        vm_size: "{{ size }}"
        admin_username: "{{ admin_uname }}"
        admin_password: "{{ admin_passwd }}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
     
    
    
    
    

 

