---
- name: ansible POST to Snow
  hosts: XXXXXXXXXX
  become: yes
  become_method: sudo

  tasks:
    - name: Posting to SNOW API
      uri:
        url: XXXXXXXXXXXXXXXXXX 
        user: "XXXXXXXXX"
        password: "XXXXXXXXXXXXX"
        method: POST
        return_content: yes
        headers:
          Content-Type: application/json
        body_format: json
        body:
          {"Name":"Ansible Tower"}
        status_code: 201
        validate_certs: no
      register: snow_response
   # - debug: 
    #    var: snow_response
     #   msg: "Test"
        
