---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: RG-GS
    vm_name: Service Now
    size: A0\Basic_A0
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis

  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
      resource_group: "{{ RG }}"
      name: "{{ vm_name }}"
      vm_size: "{{ size }}"
      admin_username: "{{ admin_uname }}"
      admin_password: "{{ admin_passwd }}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
      delegate_to: localhost
   
