---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo

tasks
 
- name:  check sonar web is up
  uri:
    url: http://sonarhost:9000/sonar/api/system/status
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
    register: output

  - name: debug
     debug: 
      var: output  
