---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
   #- vars.yml

  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: RG-GS
        name: Service Now
        vm_size: Standard_A1
        admin_username: snow
        admin_password: snowpwd
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
