---
- name: ansible POST to Snow
  hosts: localhost

  tasks:
    - name: Posting to SNOW API
      uri:
        url: https://devoteamfrdev.service-now.com//api/devo2/ansible_get/get
        user: "denis"
        password: "denis"
        method: POST
        return_content: yes
        headers:
          Content-Type: application/json
        body_format: json
        body:
          {"Name":"Ansible Tower"}
        status_code: 201
        validate_certs: no
      register: snow_response
