---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: myResourceGroup
    vm_name: TestOfficiel
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis
  tasks:
    - name: Post
      uri:
        url: https://vmlabsnowazurerh7.westeurope.cloudapp.azure.com/api/v2/job_templates/26/launch/
        user: "yfatou"
        password: "Devoteam2018!"
        method: POST
        return_content: yes
        headers:
          Content-Type: application/json
        status_code: 201
        validate_certs: no
      register: snow_response
    - debug:
        var: snow_response

 

