---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: myResourceGroup
    vm_name: TestOfficiel
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis
  tasks:
    - name: POST
      uri:
        url: http://vmlabsnowazurerh7.westeurope.cloudapp.azure.com/api/v2/job_templates/26/launch/
        method: POST
        user: "yfatou"
        password: "Devoteam2018!"
        return_content: yes
        
        force_basic_auth: yes
        validate_certs: false
        #st#tus_code: 200,404
      register: request
    - debug:
        var: request

 

