---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    name_vm: '{{ foo }}'
    RG: myResourceGroup
    vm_name: TestOfficiel
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis
    
  tasks:
    - name: Print 
      debug: msg="version - '{{ foo }}'"
     
    
    
    
    

 

