---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo

  tasks:
    - name: GET
      uri:
        url: https://vmlabsnowazurerh7.westeurope.cloudapp.azure.com/api/v1/job_templates/26/launch/
        method: GET
        return_content: yes
        status_code: 201
        body_format: json
        register: sonar_web_api_status_output
    - debug:
        var: sonar_web_api_status_output

        
