---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  tasks:
    - name: GET
      uri:
        url: http://vmlabsnowazurerh7.westeurope.cloudapp.azure.com/api/v1/job_templates/26/launch/
        user: "yfatou"
        password: "Devoteam2018!"
        method: GET
        headers:
           Authorization: "Token 16d3f50e7fda471a3d292486e5d3dd8f8e577a5b"
           Content-Type: "application/json"
        return_content: yes
        status_code: 200
        validate_certs: false
        body_format: json
        register: sonar_web_api_status_output
    - debug:
        var: sonar_web_api_status_output

 

