---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: myResourceGroup
    vm_name: TestOfficiel
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis
  tasks:
    - name: CmdLine JSON - string
      debug:
       msg: "{{ my_string }}"

    - name: CmdLine JSON - float
      debug:
       msg: "Passed float: {{ my_float }}; Subtracted from 1.0: {{ 1.0 - my_float }}"

    - name: CmdLine JSON - list
      debug:
       msg: "{{ item }}"
      with_items: "{{ my_list }}"
