---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  tasks:
  - name: Create VM with defaults
    azure_rm_virtualmachine:
      resource_group: RG-GS
      name: myVM
      vm_size: A0\Basic_A0
      admin_username: yaye
      admin_password: Devoteam18!
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
      
   
