---
- hosts: https://vmlabsnowazurerh7.westeurope.cloudapp.azure.com
  become: yes
  become_method: sudo
  vars:
    vmname: myvmname

  tasks:
  - name: POST
    uri:
      url: https://devoteamfrdev.service-now.com
      method: POST
      body:
          extra_vars:
            VmName: "{{ vmname }}"
      status_code: 200
      body_format: json

