---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  tasks:
  - name: Create VM with defaults
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: yaye
      admin_password: Devoteam18!
      image:i
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
      
   
