---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: myResourceGroup
    vm_name: Service Now
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowteam18!


tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ RG }}"
      name: testvn001
      address_prefixes: "10.10.0.0/16
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3Nz{snip}hwhqT9h"
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest
      

