---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo

  tasks
  
    - name: GET
      uri:
        url: http://sonarhost:9000/sonar/api/system/status
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
        register: sonar_web_api_status_output
        
      
    - name: debug
       debug: 
         var: sonar_web_api_status_output  


        
