---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: myResourceGroup
    vm_name: TestOfficiel
    size: Standard_A1
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis
  tasks:
    - name: GET
      uri:
        url: http://vmlabsnowazurerh7.westeurope.cloudapp.azure.com/api/v1/job_templates/26/launch/
        method: GET
        user: "yfatou"
        password: "Devoteam2018!"
        force_basic_auth: yes
        #st#tus_code: 200,404
        timeout: 10
      register: request
    - debug:
        var: request

 

