---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    vmname: myvmname

  tasks:
  - name: POST
    uri:
      url: http://vmlabsnowazurerh7.westeurope.cloudapp.azure.com/api/v1/job_templates/26/launch/
      method: POST
      body:
          extra_vars:
            VmName: "{{ vmname }}"
      status_code: 200
      body_format: json

