---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo

  tasks:
  - name: POST
    uri:
      url: https://devoteamfrdev.service-now.com
      method: POST
      body:
          extra_vars:
            Username: mytppuser
            Password: Sup3rS3cr3t
      status_code: 200
      body_format: json
