---
- hosts: vmlabsnowazuerh7
  become: yes
  become_method: sudo
  vars:
    RG: RG-GS
    vm_name: Service Now2
    size: A0\Basic_A0
    admin_uname: snow
    admin_passwd: snowDevoteam18!
    user_snow: denis
    passwd_snow: denis

  tasks:
    - name: Posting to SNOW API
      uri:
        url: https://devoteamfrdev.service-now.com/api/devo2/ansible_get/Post
        user: "{{user_snow }}"
        password: "{{user_snow }}"
        method: POST
        return_content: yes
        headers:
          Content-Type: application/json
        body_format: json
        body:
          {"Name":"{{ vm_name }}",
           "OperatingSystem":"CentOS"
          }
        #status_code: 201
        validate_certs: no
      register: snow_response
    - debug:
        var: snow_response

